// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llmvkdufjztjhlaimcdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsbXZrZHVmanp0amhsYWltY2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDA0NjYsImV4cCI6MjA2Mzg3NjQ2Nn0.jlLBcJqe2r6dA-ZFcmXuma-L64Q5Ki-1lalsazl7xDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);